### ISSUE TITLE
Cookiecutter new example creation missing some attributes

### ISSUE THREAD

**Issue by hina-shah** [InsightSoftwareConsortium/ITKExamples#136]
While creating a new example using cookiecutter
`python3 -m cookiecutter /path/to/src/ITKEx/Utilities/CookieCutter`, it gives the following error:
`Unable to render variable 'download_url'
Error message: 'dict object' has no attribute 'group_name'`

Additionally, the documentation needs to be updated to reflect deprecated `CreateNewExample.py` script.

**Comment by jhlegarreta** [comment]
@hina-shah thanks for the issue report !

Yes, you are right, and I am the one to blame on for this. Following a private email thread early May with @thewtex @dzenanz @phcerdan @fbudin69500 and @hjmjohnson about the tasks concerning the ITK Examples, it was decided that using `cookiecuter` would ease the process of creating new examples.

I did a first effort in PR #101, but the process turned out not to be so easy to put in place, so PR #120 has been progress for some time to try to fix things.

Yet, for the reasons that are explained in this PR's comments and updates, some aspects are still to be fixed.

@thewtex and I plan to finish it whenever he gets some time.

But yes, at present we need to use the ancient `Utilities/CreateNewExample.py.in` script: you'd need to use the pre- 876336f commit to get that right.

I know this is not ideal, and has made @mseng10 and @hjmjohnson 's impressive effort to transition Wiki Examples more difficult, but they could do with it. In any case, I am sorry and am happy to work on it if we can think of solutions to the challenges that have arisen following the use of `cookiecutter`.

**Comment by hina-shah** [comment]
Ah I see. I looked at the issues list but missed out on checking the PR's. Thanks for clarification! I think this issue does not make sense in that case. I'll close it, and see if I can work with a pre-commit.
