### ISSUE TITLE
Submodules ordering on the examples site

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKExamples#179]
**Description**
The ITK examples index seems not to be ordered alphabetically at the submodule level
https://itk.org/ITKExamples/src/index.html

Although a search box exists, and the browsers search tool can be used to look for the module of interest, I'd dare to say that it would be nice if the submodules were ordered alphabetically.

**Comment by jhlegarreta** [comment]
@mseng10  looks like the latest builds are still not showing a consistent/alphabetical ordering of the submodules. So not sure if the issue has been solved :-S .

**Comment by mseng10** [comment]
@jhlegarreta It appears this is the case. Thank you for catching this. I will reopen the issue and address it in a coming PR.

**Comment by mseng10** [comment]
@jhlegarreta @thewtex Should the name for a particular example's directory be the same (or very close) to the header in its respective `documentation.rst`?

This is why some of the submodules contain an indexed list of examples not in alphabetical order. I had ordered them by their subdirectory paths, but when they are indexed in Sphinx, they show the headers of the examples. This subsequently led to some of them being out of order, because their subdirectory names and headers do not match.

For example, `Filtering/ImageFeature/index.rst` contains:
```
  AdditiveGaussianNoiseImageFilter/Documentation.rst
  BilateralFilterAnImage/Documentation.rst
  ComputeLaplacian/Documentation.rst
  DerivativeImage/Documentation.rst
  DetectEdgesWithCannyFilter/Documentation.rst
  ExtractContoursFromImage/Documentation.rst
  FindZeroCrossings/Documentation.rst
  LaplacianRecursiveGaussianImageFilter/Documentation.rst
  RequestedRegion/Documentation.rst
  SegmentBloodVessels/Documentation.rst
  SharpenImage/Documentation.rst
  SobelEdgeDetectionImageFilter/Documentation.rst
  ZeroCrossingBasedEdgeDecor/Documentation.rst
```
Because the headers for the examples are what's shown on Sphinx and some of the headers do not match their respective directory name, the output in Sphinx looks like this:
![Screen Shot 2021-03-02 at 11 47 53 AM](https://user-images.githubusercontent.com/42974718/109691530-28ac2280-7b4d-11eb-8f69-f949bcc65423.png)

I think is would be easier to make each example's header the same (or very similar i.e. including parentheses, etc.) as the name of the directory it is in. Most of the other example's already adhere to this and this way we can easily order them by subdirectory in the parent directory's `index.rst`.

**Comment by mseng10** [comment]
@jhlegarreta @thewtex Also, there is inconsistency for prepositions and conjunctions in example headers. Some of the examples have them capitalized and some do not. Should these all be changed to adhere to the common rules regarding capitalization in headers i.e. MLA, APA, etc.?

**Comment by jhlegarreta** [comment]
Thanks for investigating this.

> @jhlegarreta @thewtex Should the name for a particular example's directory be the same (or very close) to the header in its respective documentation.rst?
> I think is would be easier to make each example's header the same (or very similar i.e. including parentheses, etc.) as the name of the directory it is in. Most of the other example's already adhere to this and this way we can easily order them by subdirectory in the parent directory's index.rst.

Not sure what is the best way to solve this. Having a descriptive title for what the example actually contains is very helpful and descriptive. Users will usually not see/pay attention to how the folder is called in the code. And what is shown/Sphinx shows is alphabetically ordered, which makes it easy to follow I'd say. At the same time, the shown folder names make sense from the developers' point of view. So I'd say that this is fine.

In reality, I was more concerned about the modules (namely, the `Filtering`, `IO` and `Segmentation` modules), where I cannot see that they are following the same logic since the folder corresponds exactly to the name in the index.

> @jhlegarreta @thewtex Also, there is inconsistency for prepositions and conjunctions in example headers. Some of the examples have them capitalized and some do not. Should these all be changed to adhere to the common rules regarding capitalization in headers i.e. MLA, APA, etc.?

I am fine if capitalization is applied to all letters or if a tool for specialized (e.g. leaving out definite articles, prepositions, etc.) capitalization is found. Acronyms should be capitalized I'd say.

**Comment by thewtex** [comment]
In terms of the module or example listing order, the seemingly random order is an artifact of the CreateExample script. Currently, when a new example is added, its module and example name is appended at the end of the current contents. The order could be corrected. Maybe the script could be made smarter.

+1 to a consistent capitalization, following MLA, etc.

**Comment by jhlegarreta** [comment]
@mseng10 hats off to the tremendous work in PR #228. Thanks also to @thewtex.
